import { authorizeProjectRequest } from '../../../lib/server/projectAuthorization';
import { recordWorkflowEvent, resolveWorkflowRecipients } from '../../../lib/server/workflowEvents';

export const dynamic = 'force-dynamic';
const poStates = new Set(['draft', 'approved', 'ordered', 'partially_delivered', 'delivered', 'cancelled']);
const storeStates = new Set(['available', 'low_stock', 'ordered', 'inactive']);
const text = (value: unknown, max = 300) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const number = (value: unknown) => Number(value);
const validDate = (value: unknown) => !value || (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value));
const fail = (error: string, status = 400) => Response.json({ error }, { status });

function orderInput(value: unknown) { const x = value as Record<string, unknown>; const quantity = number(x.quantity), unit_rate = number(x.unit_rate), delivered_quantity = number(x.delivered_quantity || 0); if (!x || !text(x.po_number) || !text(x.vendor) || !text(x.item) || !text(x.unit) || ![quantity, unit_rate, delivered_quantity].every(Number.isFinite) || quantity <= 0 || unit_rate < 0 || delivered_quantity < 0 || delivered_quantity > quantity || !poStates.has(text(x.status)) || !validDate(x.order_date) || !validDate(x.delivery_date)) return null; return { po_number:text(x.po_number,120), vendor:text(x.vendor), item:text(x.item), unit:text(x.unit,40), quantity, unit_rate, delivered_quantity, status:text(x.status), required_date:text(x.order_date,10)||null, expected_date:text(x.delivery_date,10)||null, order_date:text(x.order_date,10)||null, delivery_date:text(x.delivery_date,10)||null, remarks:text(x.remarks,2000)||null, responsible_person_id:text(x.responsible_person_id,80)||null }; }
function storeInput(value: unknown, creating = false) { const x=value as Record<string,unknown>; const reorderLevel=number(x?.reorder_level||0), openingStock=number(x?.opening_stock||0); if(!x||!text(x.item_code)||!text(x.item_name)||!text(x.unit)||!text(x.location)||!Number.isFinite(reorderLevel)||reorderLevel<0||!storeStates.has(text(x.status))||(creating&&(!Number.isFinite(openingStock)||openingStock<0)))return null; const shared={ item_code:text(x.item_code,120),item_name:text(x.item_name),unit:text(x.unit,40),location:text(x.location),vendor:text(x.vendor)||null,status:text(x.status),reorder_level:reorderLevel }; return creating?{...shared,opening_stock:openingStock,received:0,issued:0,inventory_opening_balance:openingStock}:shared; }

async function responsiblePerson(actor: Awaited<ReturnType<typeof authorizeProjectRequest>>, personId: string | null) {
  if (!personId || 'error' in actor) return personId;
  const [{ data: member }, { data: assignment }] = await Promise.all([
    actor.admin.from('project_users').select('auth_user_id').eq('project_id', actor.project.id).eq('auth_user_id', personId).maybeSingle(),
    actor.admin.from('project_person_assignments').select('person_id,start_date,end_date').eq('project_id', actor.project.id).eq('person_id', personId).maybeSingle(),
  ]);
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kathmandu', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
  return member && assignment && assignment.start_date <= today && (!assignment.end_date || assignment.end_date >= today) ? personId : undefined;
}

export async function GET(request: Request) { const projectId=new URL(request.url).searchParams.get('projectId')||''; const actor=await authorizeProjectRequest(request,projectId,'procurement','read'); if('error'in actor)return fail(actor.error,actor.status); const [orders,items,events]=await Promise.all([actor.admin.from('procurement_orders').select('*').eq('project_id',projectId).order('po_number'),actor.admin.from('store_items').select('*').eq('project_id',projectId).order('item_code'),actor.admin.from('inventory_events').select('*').eq('project_id',projectId).order('event_date',{ascending:false})]); if(orders.error||items.error||events.error)return fail('Procurement records could not be loaded.'); return Response.json({orders:orders.data||[],items:items.data||[],events:events.data||[]},{headers:{'Cache-Control':'no-store'}}); }
export async function POST(request: Request) { const body=await request.json().catch(()=>null) as Record<string,unknown>|null; const projectId=text(body?.projectId,120); const actor=await authorizeProjectRequest(request,projectId,'procurement','write'); if('error'in actor)return fail(actor.error,actor.status); const kind=text(body?.kind); const input=kind==='order'?orderInput(body?.record):kind==='store'?storeInput(body?.record,true):null; if(!input)return fail('Valid project-scoped procurement values are required.'); const order=kind==='order'?input as NonNullable<ReturnType<typeof orderInput>>:null; const id=text((body?.record as Record<string,unknown>)?.id,160)||`${kind}-${crypto.randomUUID()}`; const table=kind==='order'?'procurement_orders':kind==='store'?'store_items':''; if(!table)return fail('Unsupported procurement record.'); const responsible=order?await responsiblePerson(actor,order.responsible_person_id):null; if(order&&order.responsible_person_id&&responsible===undefined)return fail('The responsible person needs an active assignment in this project.',400); const saved=await actor.admin.from(table).insert({id,project_id:projectId,...input,...(order?{responsible_person_id:responsible}: {})}).select('*').single(); if(saved.error)return fail(saved.error.code==='23505'?'That project reference already exists.':'Procurement record could not be created.'); return Response.json({record:saved.data},{status:201}); }
export async function PATCH(request: Request) { const body=await request.json().catch(()=>null) as Record<string,unknown>|null; const projectId=text(body?.projectId,120),kind=text(body?.kind),id=text(body?.id,160); const actor=await authorizeProjectRequest(request,projectId,'procurement','write'); if('error'in actor)return fail(actor.error,actor.status); const input=kind==='order'?orderInput(body?.record):kind==='store'?storeInput(body?.record):null; const order=kind==='order'?input as NonNullable<ReturnType<typeof orderInput>>:null; const table=kind==='order'?'procurement_orders':kind==='store'?'store_items':''; if(!table||!id||!input)return fail('Valid procurement update is required.'); const current=await actor.admin.from(table).select('*').eq('id',id).eq('project_id',projectId).maybeSingle(); if(!current.data)return fail('Project procurement record was not found.',404); if(kind==='order'&&['delivered','cancelled'].includes(current.data.status))return fail('Delivered or cancelled purchase orders are historical and cannot be edited.',409); const responsible=order?await responsiblePerson(actor,order.responsible_person_id):null; if(order&&order.responsible_person_id&&responsible===undefined)return fail('The responsible person needs an active assignment in this project.',400); const saved=await actor.admin.from(table).update({...input,...(order?{responsible_person_id:responsible}: {})}).eq('id',id).eq('project_id',projectId).select('*').single(); if(saved.error)return fail('Procurement record could not be updated.');
  if (kind === 'order' && current.data.status !== saved.data.status) {
    const transition = `${current.data.status}_to_${saved.data.status}`;
    const eventType = transition === 'draft_to_approved' ? 'PROCUREMENT_ORDER_APPROVED' : transition === 'approved_to_ordered' ? 'PROCUREMENT_ORDER_ORDERED' : '';
    if (eventType) {
      const event = { organizationId: actor.project.organizationId, projectId, departmentKey: 'procurement', eventType, sourceType: 'procurement_order', sourceId: id, actorUserId: actor.userId, dedupeKey: `project:${projectId}:procurement-order:${id}:${transition}`, metadata: { title: eventType === 'PROCUREMENT_ORDER_APPROVED' ? `Purchase order ${saved.data.po_number} approved` : `Purchase order ${saved.data.po_number} placed`, poNumber: saved.data.po_number, transition } };
      const recipients = await resolveWorkflowRecipients(actor.admin, event);
      await recordWorkflowEvent(actor.admin, event, recipients);
    }
  }
  if (kind === 'order' && current.data.responsible_person_id !== saved.data.responsible_person_id && saved.data.responsible_person_id) {
    const event = { organizationId: actor.project.organizationId, projectId, departmentKey: 'procurement', eventType: 'PROCUREMENT_ORDER_ASSIGNED', sourceType: 'procurement_order', sourceId: id, actorUserId: actor.userId, dedupeKey: `project:${projectId}:procurement-order:${id}:responsible:${saved.data.responsible_person_id}`, metadata: { title: `Purchase order ${saved.data.po_number} assigned to you`, poNumber: saved.data.po_number } };
    await recordWorkflowEvent(actor.admin, event, [saved.data.responsible_person_id]);
  }
  return Response.json({record:saved.data}); }
