import { authorizeProjectRequest } from '../../../lib/server/projectAuthorization';

export const dynamic = 'force-dynamic';
const poStates = new Set(['draft', 'approved', 'ordered', 'partially_delivered', 'delivered', 'cancelled']);
const storeStates = new Set(['available', 'low_stock', 'ordered', 'inactive']);
const text = (value: unknown, max = 300) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const number = (value: unknown) => Number(value);
const validDate = (value: unknown) => !value || (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value));
const fail = (error: string, status = 400) => Response.json({ error }, { status });

function orderInput(value: unknown) { const x = value as Record<string, unknown>; const quantity = number(x.quantity), unit_rate = number(x.unit_rate), delivered_quantity = number(x.delivered_quantity || 0); if (!x || !text(x.po_number) || !text(x.vendor) || !text(x.item) || !text(x.unit) || ![quantity, unit_rate, delivered_quantity].every(Number.isFinite) || quantity <= 0 || unit_rate < 0 || delivered_quantity < 0 || delivered_quantity > quantity || !poStates.has(text(x.status)) || !validDate(x.order_date) || !validDate(x.delivery_date)) return null; return { po_number:text(x.po_number,120), vendor:text(x.vendor), item:text(x.item), unit:text(x.unit,40), quantity, unit_rate, delivered_quantity, status:text(x.status), required_date:text(x.order_date,10)||null, expected_date:text(x.delivery_date,10)||null, order_date:text(x.order_date,10)||null, delivery_date:text(x.delivery_date,10)||null, remarks:text(x.remarks,2000)||null }; }
function storeInput(value: unknown) { const x=value as Record<string,unknown>; const values=['opening_stock','received','issued','reorder_level'].map(key=>number(x[key]||0)); if(!x||!text(x.item_code)||!text(x.item_name)||!text(x.unit)||!text(x.location)||!values.every(value=>Number.isFinite(value)&&value>=0)||!storeStates.has(text(x.status)))return null; return { item_code:text(x.item_code,120),item_name:text(x.item_name),unit:text(x.unit,40),location:text(x.location),vendor:text(x.vendor)||null,status:text(x.status),opening_stock:values[0],received:values[1],issued:values[2],reorder_level:values[3] }; }

export async function GET(request: Request) { const projectId=new URL(request.url).searchParams.get('projectId')||''; const actor=await authorizeProjectRequest(request,projectId,'procurement','read'); if('error'in actor)return fail(actor.error,actor.status); const [orders,items,events]=await Promise.all([actor.admin.from('procurement_orders').select('*').eq('project_id',projectId).order('po_number'),actor.admin.from('store_items').select('*').eq('project_id',projectId).order('item_code'),actor.admin.from('inventory_events').select('*').eq('project_id',projectId).order('event_date',{ascending:false})]); if(orders.error||items.error||events.error)return fail('Procurement records could not be loaded.'); return Response.json({orders:orders.data||[],items:items.data||[],events:events.data||[]},{headers:{'Cache-Control':'no-store'}}); }
export async function POST(request: Request) { const body=await request.json().catch(()=>null) as Record<string,unknown>|null; const projectId=text(body?.projectId,120); const actor=await authorizeProjectRequest(request,projectId,'procurement','write'); if('error'in actor)return fail(actor.error,actor.status); const kind=text(body?.kind); const input=kind==='order'?orderInput(body?.record):storeInput(body?.record); if(!input)return fail('Valid project-scoped procurement values are required.'); const id=text((body?.record as Record<string,unknown>)?.id,160)||`${kind}-${crypto.randomUUID()}`; const table=kind==='order'?'procurement_orders':kind==='store'?'store_items':''; if(!table)return fail('Unsupported procurement record.'); const saved=await actor.admin.from(table).insert({id,project_id:projectId,...input}).select('*').single(); if(saved.error)return fail(saved.error.code==='23505'?'That project reference already exists.':'Procurement record could not be created.'); return Response.json({record:saved.data},{status:201}); }
export async function PATCH(request: Request) { const body=await request.json().catch(()=>null) as Record<string,unknown>|null; const projectId=text(body?.projectId,120),kind=text(body?.kind),id=text(body?.id,160); const actor=await authorizeProjectRequest(request,projectId,'procurement','write'); if('error'in actor)return fail(actor.error,actor.status); const input=kind==='order'?orderInput(body?.record):storeInput(body?.record); const table=kind==='order'?'procurement_orders':kind==='store'?'store_items':''; if(!table||!id||!input)return fail('Valid procurement update is required.'); const current=await actor.admin.from(table).select('*').eq('id',id).eq('project_id',projectId).maybeSingle(); if(!current.data)return fail('Project procurement record was not found.',404); if(kind==='order'&&['delivered','cancelled'].includes(current.data.status))return fail('Delivered or cancelled purchase orders are historical and cannot be edited.',409); const saved=await actor.admin.from(table).update(input).eq('id',id).eq('project_id',projectId).select('*').single(); if(saved.error)return fail('Procurement record could not be updated.'); return Response.json({record:saved.data}); }
