import React, { useEffect, useState } from 'react';
import { storage } from '../lib/storage';
import { PageHeader } from './ManagementUI';

export default function CompanyAdminDashboard() {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const headers = async (): Promise<Record<string, string>> => { const session = await storage.getAuthSession(); return session ? { Authorization: `Bearer ${session.access_token}` } : {}; };
  const load = async () => { setLoading(true); try { const response = await fetch('/api/company-admin', { headers: await headers(), cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : 'Company administration is unavailable.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const updateStatus = async (memberId: string, status: string) => { const response = await fetch('/api/company-admin', { method: 'PATCH', headers: { ...(await headers()), 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'membership', memberId, status }) }); const result = await response.json(); if (!response.ok) return setMessage(result.error || 'Could not update membership.'); setMessage(`Membership ${status}.`); void load(); };
  if (loading) return <div className="rounded-xl border border-slate-200 bg-white p-5 text-sm text-slate-600">Loading company administration…</div>;
  if (!data) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950">{message || 'Company administration is unavailable.'}</div>;
  const organization = data.organization;
  return <section className="space-y-6"><PageHeader eyebrow="Company administration" title={organization.name} description="Manage your company profile, members and subscription visibility. Project access remains managed separately." />
    {message && <div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-950">{message}</div>}
    <div className="grid gap-4 md:grid-cols-3"><Summary label="Subscription" value={organization.subscription_status?.replace('_',' ') || 'Not set'} note={`${organization.plan || 'Plan'} · valid to ${organization.access_until || 'Not set'}`} /><Summary label="People" value={`${data.usage.seats} / ${organization.seat_limit}`} note="Active company members" /><Summary label="Projects" value={`${data.usage.projects} / ${organization.project_limit}`} note="Active projects" /></div>
    <div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-base font-semibold text-slate-950">Company profile</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Item label="Legal name" value={organization.legal_name} /><Item label="Email" value={organization.contact_email} /><Item label="Phone" value={organization.phone} /><Item label="Website" value={organization.website} /><Item label="Address" value={organization.address} /></dl></div>
    <div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">Company people</h2><p className="text-sm text-slate-600">Membership controls do not automatically add or remove project assignments.</p></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="pb-2">Person</th><th className="pb-2">Role</th><th className="pb-2">Projects</th><th className="pb-2">Status</th><th className="pb-2" /></tr></thead><tbody>{data.members.map((member: any) => <tr className="border-b border-slate-100" key={member.id}><td className="py-3 font-medium text-slate-900">{member.name}<span className="block font-normal text-slate-500">{member.email}</span></td><td className="py-3 capitalize">{member.role?.replace('_',' ')}</td><td className="py-3 text-slate-600">{member.projects.map((project: any) => project.name).join(', ') || 'No project assignment'}</td><td className="py-3 capitalize">{member.status}</td><td className="py-3 text-right">{member.status === 'active' ? <button onClick={() => void updateStatus(member.id,'suspended')} className="text-sm font-semibold text-amber-700">Deactivate</button> : <button onClick={() => void updateStatus(member.id,'active')} className="text-sm font-semibold text-blue-700">Reactivate</button>}</td></tr>)}</tbody></table></div></div>
    <div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-base font-semibold text-slate-950">Enabled modules</h2><p className="mt-1 text-sm text-slate-600">This is a read-only subscription summary. Access rules are enforced separately.</p><div className="mt-3 flex flex-wrap gap-2">{data.entitlements.filter((item: any) => item.enabled).map((item: any) => <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700" key={item.module_key}>{item.module_key.replace('_',' ')}</span>)}</div></div>
  </section>;
}
function Summary({label,value,note}:{label:string;value:string;note:string}) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold capitalize text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>; }
function Item({label,value}:{label:string;value?:string|null}) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-slate-800">{value || 'Not provided'}</dd></div>; }
