'use client';
import React, { useMemo, useState } from 'react';
import type { Activity } from '../lib/cpm';
import { storage } from '../lib/storage';
import { workItems } from '../lib/workAdapter';
import WorkBoardBase from './work/WorkBoard';
const WorkBoard = ({ items, onNavigate }: { items: ReturnType<typeof workItems>; onNavigate: (tab: string) => void }) => <WorkBoardBase items={items} onNavigate={onNavigate} onRefresh={() => window.location.reload()} />;
const departments = [
  { id:'site', icon:'🏗️', name:'Project / Site', text:'Today’s work, site reports, photos and progress.', tools:[['daily','Site Reports'],['cpm','Site Activities'],['evidence','Photos'],['expected_actual','Progress']] },
  { id:'procurement', icon:'🛒', name:'Procurement', text:'Buying materials, services and project requirements.', tools:[['procurement','Procurement & purchase orders'],['reports','Reports']] },
  { id:'stores', icon:'📦', name:'Stores / Warehouse', text:'Stock, receiving and project materials.', tools:[['procurement','Stock / Stores'],['reports','Reports']] },
  { id:'finance', icon:'💰', name:'Finance', text:'Costs, payments, expenses and financial reports.', tools:[['budget','Cost Control'],['ipc','Payments'],['expenses','Expenses'],['reports','Reports']] },
  { id:'hr', icon:'👥', name:'HR / People', text:'People, project assignments and workforce records.', tools:[['people','People & Assignments'],['operations','Workforce']] },
  { id:'equipment', icon:'🚜', name:'Equipment', text:'Available equipment and resource usage tools.', tools:[['operations','Equipment']] },
  { id:'commercial', icon:'📐', name:'Commercial / QS', text:'BOQ, valuation, changes and claims.', tools:[['cpm','BOQ'],['ipc','Valuation'],['claims','Changes & Claims'],['reports','Reports']] },
  { id:'documents', icon:'📁', name:'Documents / Administration', text:'Documents, correspondence and project records.', tools:[['documents','Documents'],['evidence','Evidence'],['reports','Reports']] },
  { id:'qaqc', icon:'🧪', name:'QA/QC', text:'Available quality tools for this project.', tools:[['qaqc','QA/QC tools']] },
  { id:'safety', icon:'🦺', name:'Safety', text:'Available safety tools for this project.', tools:[['safety','Safety tools']] },
];
export default function DepartmentsWorkspace({ projectId, activities, onNavigate }: { projectId:string; activities:Activity[]; onNavigate:(tab:string)=>void }) { const [selected,setSelected]=useState<string|null>(null); const all=useMemo(()=>workItems(projectId,activities,storage.getProcurementOrders()),[projectId,activities]); const current=departments.find(item=>item.id===selected); const filtered=current ? all.filter(item=>current.id==='site'?item.source==='activity':current.id==='procurement'||current.id==='stores'?item.source==='procurement':false) : []; if(current) return <div className="space-y-6"><button onClick={()=>setSelected(null)} className="text-sm font-bold text-blue-800">← All departments</button><div><p className="text-sm font-bold text-blue-800">{current.name}</p><h1 className="text-2xl font-extrabold text-slate-950">{current.name}</h1><p className="mt-1 text-slate-600">{current.text}</p></div><div className="flex flex-wrap gap-2">{current.tools.map(([tab,label])=><button key={label} onClick={()=>onNavigate(tab)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-800">{label}</button>)}</div>{filtered.length?<WorkBoard items={filtered} onNavigate={onNavigate}/>:<div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-bold text-slate-950">Work</h2><p className="mt-1 text-sm text-slate-600">This department’s existing tools are available above. A safe shared Work adapter is not available yet.</p></div>}</div>; return <div className="space-y-6"><div><h1 className="text-2xl font-extrabold text-slate-950">Departments</h1><p className="mt-1 text-slate-600">Choose an area to see its work, people and the tools already available.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{departments.map(department=>{const rows=department.id==='site'?all.filter(item=>item.source==='activity'):['procurement','stores'].includes(department.id)?all.filter(item=>item.source==='procurement'):[]; const counts=['new','in_progress','waiting','completed'].map(stage=>rows.filter(item=>item.stage===stage).length); return <button key={department.id} onClick={()=>setSelected(department.id)} className="min-h-48 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm hover:border-blue-300"><span className="text-3xl">{department.icon}</span><h2 className="mt-3 font-extrabold text-slate-950">{department.name}</h2><p className="mt-1 text-sm text-slate-500">{department.text}</p><p className="mt-4 text-xs font-bold text-slate-600">New {counts[0]} · Working {counts[1]} · Waiting {counts[2]} · Done {counts[3]}</p><p className="mt-3 text-sm font-bold text-blue-800">Open department →</p></button>})}</div></div>; }
