'use client';

import { useEffect, useMemo, useState } from 'react';
import { storage } from '../lib/storage';
import { previewKind } from '../lib/documentVault';

const modules = ['Documents', 'Site', 'Tasks', 'Finance', 'Billing', 'Procurement', 'Stores', 'Equipment', 'HR', 'Commercial', 'QA/QC', 'HSE'];
const categories = ['Project', 'Site', 'Task', 'Finance', 'Payment', 'Procurement', 'Stores', 'Equipment', 'HR', 'Contract', 'Commercial', 'QA/QC', 'HSE', 'Photo', 'Report', 'Certificate', 'Other'];
const today = () => new Date().toISOString().slice(0, 10);

export default function DocumentVault({ projectId }: { projectId: string }) {
  const [data, setData] = useState<{ documents: any[]; history: any[] }>({ documents: [], history: [] }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [query, setQuery] = useState(''); const [view, setView] = useState<'list'|'images'>('list'); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<any>(null); const [file, setFile] = useState<File | null>(null);
  const [form, setForm] = useState({ title: '', module: 'Documents', category: 'Other', status: 'COMPLETED', documentNumber: '', revision: '', documentDate: today(), siteName: '', taskName: '', description: '', tags: '' });
  const headers = async () => ({ Authorization: `Bearer ${(await storage.getAuthSession())?.access_token || ''}` });
  const load = async () => { const response = await fetch(`/api/document-vault?projectId=${encodeURIComponent(projectId)}${query ? `&q=${encodeURIComponent(query)}` : ''}${view === 'images' ? '&kind=images' : ''}`, { headers: await headers(), cache: 'no-store' }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || 'Document Vault is unavailable.'); else { setData(payload); setError(''); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId, query, view]);
  const upload = async (event: React.FormEvent) => { event.preventDefault(); if (!file) return setError('Choose a file to upload.'); setBusy(true); setError(''); setNotice('Uploading to Google Drive…'); const payload = new FormData(); payload.append('file', file); payload.append('projectId', projectId); Object.entries(form).forEach(([key, value]) => payload.append(key, value)); payload.append('source', 'WEB'); payload.append('idempotencyKey', crypto.randomUUID()); const response = await fetch('/api/document-vault', { method: 'POST', headers: await headers(), body: payload }); const result = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setError(result.error || 'Upload failed. No document reference was created.'); setNotice(''); return; } setNotice('Saved to Google Drive and indexed in CTMS.'); setFile(null); setForm({ ...form, title: '', documentNumber: '', revision: '', siteName: '', taskName: '', description: '', tags: '' }); await load(); };
  const imageDocuments = useMemo(() => data.documents.filter(item => previewKind(item.mime_type || '', item.file_name) === 'image'), [data.documents]);
  const updateStatus = async (documentId: string, status: string) => { setBusy(true); const response = await fetch('/api/document-vault', { method: 'PATCH', headers: { ...(await headers()), 'Content-Type': 'application/json' }, body: JSON.stringify({ projectId, action: 'status', documentId, status }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(payload.error || 'Document status could not be changed.'); else { setNotice('Document status updated.'); await load(); } };
  return <section className="space-y-5"><header className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Document Vault</h2><p className="mt-1 text-sm text-slate-600">One CTMS index over private tenant Google Drive files. Business records remain the source of truth.</p></header>{error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-900">{error}</p>}{notice && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{notice}</p>}
    <form onSubmit={upload} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold text-slate-900">Upload to Google Drive</h3><div className="mt-3 grid gap-3 md:grid-cols-3"><Input label="File" type="file" required onChange={value => setFile(value as File)} /><Input label="Title" required value={form.title} onChange={title => setForm({ ...form, title: String(title) })}/><Select label="Module" value={form.module} values={modules} onChange={module => setForm({ ...form, module })}/><Select label="Category" value={form.category} values={categories} onChange={category => setForm({ ...form, category })}/><Input label="Document number" value={form.documentNumber} onChange={documentNumber => setForm({ ...form, documentNumber: String(documentNumber) })}/><Input label="Revision" value={form.revision} onChange={revision => setForm({ ...form, revision: String(revision) })}/><Input label="Document date" type="date" value={form.documentDate} onChange={documentDate => setForm({ ...form, documentDate: String(documentDate) })}/><Input label="Site / area" value={form.siteName} onChange={siteName => setForm({ ...form, siteName: String(siteName) })}/><Input label="Task name" value={form.taskName} onChange={taskName => setForm({ ...form, taskName: String(taskName) })}/><Input label="Tags" value={form.tags} onChange={tags => setForm({ ...form, tags: String(tags) })}/><Input label="Description" value={form.description} onChange={description => setForm({ ...form, description: String(description) })}/></div><button disabled={busy} className="mt-4 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{busy ? 'Uploading…' : 'Upload and index'}</button></form>
    <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row md:items-center md:justify-between"><div className="flex gap-2"><button onClick={() => setView('list')} className={view === 'list' ? 'rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white' : 'rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700'}>Documents</button><button onClick={() => setView('images')} className={view === 'images' ? 'rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white' : 'rounded-lg border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700'}>Images</button></div><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search file, title, number…" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 md:w-80"/></div>
    {view === 'images' ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{imageDocuments.map(document => <button key={document.id} onClick={() => setSelected(document)} className="overflow-hidden rounded-xl border border-slate-200 bg-white text-left shadow-sm"><img src={`https://drive.google.com/thumbnail?id=${encodeURIComponent(document.google_drive_file_id)}&sz=w640`} alt={document.title} className="h-40 w-full object-cover"/><div className="p-3"><b className="block text-sm text-slate-900">{document.title}</b><span className="text-xs text-slate-600">{document.uploaded_by_name} · {String(document.uploaded_at).slice(0, 10)}</span></div></button>)}{!imageDocuments.length && <p className="col-span-full rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500">No images match this filter.</p>}</div> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr><th className="p-3">File</th><th className="p-3">Module</th><th className="p-3">Uploader</th><th className="p-3">Date</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{data.documents.map(document => <tr key={document.id} className="border-t border-slate-100"><td className="p-3"><b className="text-slate-900">{document.title}</b><span className="block text-xs text-slate-600">{document.file_name} · {document.revision || `v${document.version_number}`}</span></td><td className="p-3">{document.module}</td><td className="p-3">{document.uploaded_by_name}<span className="block text-xs text-slate-600">{document.uploaded_by_department}</span></td><td className="p-3">{String(document.uploaded_at).slice(0, 10)}</td><td className="p-3"><button disabled={busy} onClick={() => void updateStatus(document.id, document.status === 'ARCHIVED' ? 'COMPLETED' : 'ARCHIVED')} className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">{document.status}</button></td><td className="p-3"><button onClick={() => setSelected(document)} className="font-bold text-blue-700">Preview</button></td></tr>)}{!data.documents.length && <tr><td colSpan={6} className="p-6 text-center text-slate-500">No indexed documents yet.</td></tr>}</tbody></table></div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-xl bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{selected.title}</h3><p className="text-sm text-slate-600">{selected.file_name} · {selected.mime_type}</p></div><button onClick={() => setSelected(null)} className="font-bold text-slate-700">Close</button></div><Preview document={selected}/><a href={selected.google_drive_web_view_link || `https://drive.google.com/open?id=${selected.google_drive_file_id}`} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold text-blue-700">Open in Drive / download</a></div></div>}
  </section>;
}
function Preview({ document }: { document: any }) { const kind = previewKind(document.mime_type || '', document.file_name); const url = `https://drive.google.com/file/d/${document.google_drive_file_id}/preview`; if (kind === 'image') return <img src={`https://drive.google.com/thumbnail?id=${encodeURIComponent(document.google_drive_file_id)}&sz=w1600`} alt={document.title} className="mt-4 max-h-[70vh] w-full object-contain"/>; if (kind === 'audio') return <audio controls className="mt-4 w-full" src={url}/>; if (kind === 'pdf') return <iframe title={document.title} src={url} className="mt-4 h-[65vh] w-full border"/>; return <div className="mt-4 rounded-lg bg-slate-50 p-6 text-sm text-slate-700">This file type is stored safely in Google Drive but cannot be previewed in CTMS. Open or download it from Drive.</div>; }
function Input({ label, value = '', type = 'text', required = false, onChange }: { label: string; value?: string; type?: string; required?: boolean; onChange: (value: string | File) => void }) { return <label className="text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span><input type={type} required={required} value={type === 'file' ? undefined : value} onChange={event => onChange(type === 'file' ? event.target.files?.[0] || '' : event.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900"/></label>; }
function Select({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="text-sm font-semibold text-slate-700"><span className="mb-1 block">{label}</span><select value={value} onChange={event => onChange(event.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900">{values.map(value => <option key={value}>{value}</option>)}</select></label>; }
