'use client';

import { useEffect, useMemo, useState } from 'react';
import BsDatePicker from './BsDatePicker';
import { storage } from '../lib/storage';

const money = (value: unknown) => new Intl.NumberFormat('en-NP', { style: 'currency', currency: 'NPR', maximumFractionDigits: 2 }).format(Number(value || 0));
const today = () => new Date().toISOString().slice(0, 10);

export default function IpcValuationWorkspace({ projectId, role }: { projectId: string; role: string }) {
  const [data, setData] = useState<any>({ periods: [], rates: [], measurements: [], eligibleMeasurements: [], lines: [], links: [], activities: [] });
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [periodForm, setPeriodForm] = useState({ referenceNumber: '', periodStart: '', periodEnd: '' });
  const [rateForm, setRateForm] = useState({ activityId: '', unitRate: '', effectiveFrom: today() });
  const canManageRates = role === 'project_director' || role === 'qs_billing_engineer'; const canReview = role === 'project_director';
  const headers = async () => ({ Authorization: `Bearer ${(await storage.getAuthSession())?.access_token || ''}`, 'Content-Type': 'application/json' });
  const load = async () => { const response = await fetch(`/api/ipc/valuation?projectId=${encodeURIComponent(projectId)}`, { headers: await headers() }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || 'IPC valuation is unavailable.'); else setData(payload); };
  // Server remains authoritative; reload after every command.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [projectId]);
  const command = async (body: any, method = 'POST') => { setBusy(true); setError(''); setMessage(''); const response = await fetch('/api/ipc/valuation', { method, headers: await headers(), body: JSON.stringify({ projectId, ...body }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(payload.error || 'Valuation action failed.'); else { setMessage('Saved.'); void load(); } };
  const byPeriod = useMemo(() => Object.fromEntries((data.periods || []).map((period: any) => [period.id, period])), [data.periods]);
  const activity = (id: string) => (data.activities || []).find((item: any) => item.id === id);
  const rate = (activityId: string) => (data.rates || []).filter((item: any) => item.activity_id === activityId).sort((a: any, b: any) => String(b.effective_from).localeCompare(String(a.effective_from)))[0];
  const linesFor = (periodId: string) => (data.lines || []).filter((line: any) => line.valuation_period_id === periodId);
  const usedDraftMeasurement = (periodId: string, measurementId: string) => (data.links || []).some((link: any) => link.valuation_period_id === periodId && link.measurement_id === measurementId);
  return <section className="space-y-5">
    <header className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">IPC valuation workspace</h2><p className="mt-1 text-sm text-slate-600">Approved BOQ measurements are valued here. Certification locks evidence; it does not mean payment.</p></header>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-900">{error}</p>}{message && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{message}</p>}
    <div className="grid gap-4 lg:grid-cols-2">
      <form onSubmit={event => { event.preventDefault(); void command({ action: 'create_period', ...periodForm }); setPeriodForm({ referenceNumber: '', periodStart: '', periodEnd: '' }); }} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold text-slate-900">Create valuation draft</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><input required value={periodForm.referenceNumber} onChange={event => setPeriodForm({ ...periodForm, referenceNumber: event.target.value })} placeholder="IPC reference" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"/><BsDatePicker value={periodForm.periodStart} onChange={value => setPeriodForm({ ...periodForm, periodStart: value })}/><BsDatePicker value={periodForm.periodEnd} onChange={value => setPeriodForm({ ...periodForm, periodEnd: value })}/></div><button disabled={busy} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">Create draft</button></form>
      {canManageRates && <form onSubmit={event => { event.preventDefault(); void command({ action: 'save_rate', activityId: rateForm.activityId, unitRate: Number(rateForm.unitRate), effectiveFrom: rateForm.effectiveFrom }); setRateForm({ ...rateForm, unitRate: '' }); }} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold text-slate-900">BOQ contract rate</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><select required value={rateForm.activityId} onChange={event => setRateForm({ ...rateForm, activityId: event.target.value })} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"><option value="">Select BOQ item</option>{(data.activities || []).map((item: any) => <option key={item.id} value={item.id}>{item.wbs_code} · {item.name}</option>)}</select><input required min="0" step="0.01" type="number" value={rateForm.unitRate} onChange={event => setRateForm({ ...rateForm, unitRate: event.target.value })} placeholder="Rate" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"/><BsDatePicker value={rateForm.effectiveFrom} onChange={value => setRateForm({ ...rateForm, effectiveFrom: value })}/></div><button disabled={busy} className="mt-3 rounded-lg border border-blue-300 px-4 py-2 text-sm font-bold text-blue-800 disabled:opacity-60">Save rate</button></form>}
    </div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr><th className="p-3">BOQ item</th><th className="p-3">Approved qty</th><th className="p-3">Current rate</th><th className="p-3">State</th></tr></thead><tbody>{(data.activities || []).map((item: any) => <tr key={item.id} className="border-t border-slate-100"><td className="p-3 font-semibold text-slate-900">{item.wbs_code} · {item.name}</td><td className="p-3">{(data.measurements || []).filter((measurement: any) => measurement.activity_id === item.id && measurement.status === 'approved').reduce((sum: number, measurement: any) => sum + Number(measurement.quantity || 0), 0)} / {item.planned_quantity} {item.unit}</td><td className="p-3">{rate(item.id) ? `${money(rate(item.id).unit_rate)} from ${rate(item.id).effective_from}` : 'Rate required'}</td><td className="p-3 text-xs text-slate-600">Measurements are selectable only when approved and not already certified.</td></tr>)}{!(data.activities || []).length && <tr><td colSpan={4} className="p-5 text-center text-slate-500">No BOQ activities are available.</td></tr>}</tbody></table></div>
    <div className="space-y-4">{(data.periods || []).map((period: any) => <article key={period.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold text-slate-900">{period.reference_number}</h3><p className="text-sm text-slate-600">{period.period_start} → {period.period_end} · <span className="font-semibold">{period.status}</span></p></div><div className="flex flex-wrap gap-2">{period.status === 'draft' && <button disabled={busy} onClick={() => void command({ periodId: period.id, action: 'submit' }, 'PATCH')} className="rounded-md bg-blue-700 px-3 py-1.5 text-xs font-bold text-white">Submit</button>}{period.status === 'submitted' && canReview && <button disabled={busy} onClick={() => void command({ periodId: period.id, action: 'review' }, 'PATCH')} className="rounded-md border border-blue-300 px-3 py-1.5 text-xs font-bold text-blue-800">Review</button>}{period.status === 'review' && canReview && <button disabled={busy} onClick={() => void command({ periodId: period.id, action: 'certify' }, 'PATCH')} className="rounded-md bg-emerald-700 px-3 py-1.5 text-xs font-bold text-white">Certify</button>}</div></div>
      {period.status === 'draft' && <div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Eligible approved measurement</th><th className="p-2">BOQ item</th><th className="p-2">Qty</th><th className="p-2">Rate</th><th className="p-2"></th></tr></thead><tbody>{(data.eligibleMeasurements || []).map((measurement: any) => { const item = activity(measurement.activity_id); const itemRate = rate(measurement.activity_id); const included = usedDraftMeasurement(period.id, measurement.id); return <tr key={measurement.id} className="border-b border-slate-100"><td className="p-2">{measurement.measurement_date}<span className="block text-xs text-slate-500">{measurement.description || '—'}</span></td><td className="p-2">{item?.wbs_code} · {item?.name || measurement.activity_id}</td><td className="p-2">{measurement.quantity}</td><td className="p-2">{itemRate ? money(itemRate.unit_rate) : 'Rate required'}</td><td className="p-2">{included ? <span className="text-xs font-bold text-emerald-700">Included</span> : <button disabled={busy || !itemRate} onClick={() => void command({ action: 'include_measurement', periodId: period.id, measurementId: measurement.id })} className="text-xs font-bold text-blue-700 disabled:opacity-50">Include</button>}</td></tr>; })}</tbody></table></div>}
      <div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b text-left text-xs uppercase text-slate-500"><tr><th className="p-2">Valued BOQ item</th><th className="p-2">Previous</th><th className="p-2">Current</th><th className="p-2">Rate</th><th className="p-2">Current value</th><th className="p-2">Warning</th></tr></thead><tbody>{linesFor(period.id).map((line: any) => { const item = activity(line.activity_id); return <tr key={line.id} className="border-b border-slate-100"><td className="p-2 font-semibold">{item?.wbs_code} · {item?.name || line.activity_id}</td><td className="p-2">{line.previous_certified_quantity}</td><td className="p-2">{line.current_quantity}</td><td className="p-2">{money(line.unit_rate)}</td><td className="p-2 font-semibold">{money(line.current_value)}</td><td className="p-2 text-amber-800">{line.exceeds_boq ? 'Exceeds BOQ quantity' : '—'}</td></tr>; })}{!linesFor(period.id).length && <tr><td colSpan={6} className="p-3 text-slate-500">No measurements selected yet.</td></tr>}</tbody></table></div>
    </article>)}{!(data.periods || []).length && <p className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">No valuation periods yet.</p>}</div>
  </section>;
}
