'use client';
import React, { useCallback, useEffect, useState } from 'react';
import { getSupabaseClient } from '../lib/storage';

type Notification = { id: string; project_id: string; actor: string | null; action: string; module: string; detail: string | null; created_at: string; read: boolean };
async function api(path: string, init?: RequestInit) { const { data } = await getSupabaseClient()?.auth.getSession() || {}; const response = await fetch(path, { ...init, headers: { 'Content-Type': 'application/json', ...(data?.session ? { Authorization: `Bearer ${data.session.access_token}` } : {}), ...(init?.headers || {}) } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || 'Notifications could not be loaded.'); return body; }

export default function NotificationCenter({ projectId, onNavigate }: { projectId: string; onNavigate: (tab: string) => void }) {
  const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [saving, setSaving] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await api(`/api/notifications?projectId=${encodeURIComponent(projectId)}`); setItems(result.notifications || []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Notifications could not be loaded.'); } finally { setLoading(false); } }, [projectId]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const markRead = async (notificationId: string) => { setSaving(notificationId); setError(''); try { await api('/api/notifications', { method: 'PATCH', body: JSON.stringify({ projectId, notificationId }) }); setItems((current) => current.map((item) => item.id === notificationId ? { ...item, read: true } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Notification could not be updated.'); } finally { setSaving(null); } };
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-extrabold text-slate-950">Notifications</h1><p className="mt-1 text-slate-600">Your server-confirmed updates for this project.</p></div><button onClick={() => void load()} disabled={loading} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-800 disabled:opacity-60">{loading ? 'Refreshing…' : 'Refresh'}</button></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}{loading ? <p className="rounded-2xl border border-slate-200 bg-white p-6 text-slate-500">Loading notifications…</p> : <div className="space-y-3">{items.map((item) => <article key={item.id} className={`rounded-2xl border p-4 shadow-sm ${item.read ? 'border-slate-200 bg-white' : 'border-blue-200 bg-blue-50/60'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold text-slate-950">{item.action}</p><p className="mt-1 text-sm text-slate-700">{item.detail || 'Project update'}</p><p className="mt-2 text-xs text-slate-500">{item.module} · {new Date(item.created_at).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={() => onNavigate('work')} className="rounded-lg px-3 py-2 text-sm font-bold text-blue-800">Open workspace</button>{!item.read && <button disabled={saving === item.id} onClick={() => void markRead(item.id)} className="rounded-lg border border-blue-200 bg-white px-3 py-2 text-sm font-bold text-blue-800 disabled:opacity-60">{saving === item.id ? 'Saving…' : 'Mark read'}</button>}</div></div></article>)}{!items.length && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 font-semibold text-emerald-900">No server-confirmed notifications for this project.</div>}</div>}</div>;
}
