'use client';

import { useEffect, useMemo, useState } from 'react';
import BsDatePicker from './BsDatePicker';
import { storage } from '../lib/storage';
import RecordDetailsDialog from './RecordDetailsDialog';

const money = (value: unknown) => new Intl.NumberFormat('en-NP', { style: 'currency', currency: 'NPR', maximumFractionDigits: 2 }).format(Number(value || 0));
const today = () => new Date().toISOString().slice(0, 10);

export default function PaymentCertificateWorkspace({ projectId, role }: { projectId: string; role: string }) {
  const [data, setData] = useState<any>({ certificates: [], deductions: [], certifiedValuations: [] }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [form, setForm] = useState({ valuationPeriodId: '', certificateNumber: '', certificateDate: today() }); const [deduction, setDeduction] = useState({ certificateId: '', kind: 'retention', amount: '', description: '' });
  const [selectedRecord, setSelectedRecord] = useState<object | null>(null);
  const headers = async () => ({ Authorization: `Bearer ${(await storage.getAuthSession())?.access_token || ''}`, 'Content-Type': 'application/json' });
  const load = async () => { const response = await fetch(`/api/ipc/certificates?projectId=${encodeURIComponent(projectId)}`, { headers: await headers() }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error || 'Payment certificates are unavailable.'); else setData(payload); };
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [projectId]);
  const command = async (body: any, method = 'POST') => { setBusy(true); setError(''); setMessage(''); const response = await fetch('/api/ipc/certificates', { method, headers: await headers(), body: JSON.stringify({ projectId, ...body }) }); const payload = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) setError(payload.error || 'Certificate action failed.'); else { setMessage('Saved.'); void load(); } };
  const valuations = useMemo(() => Object.fromEntries((data.certifiedValuations || []).map((item: any) => [item.id, item])), [data.certifiedValuations]);
  const deductions = (certificateId: string) => (data.deductions || []).filter((item: any) => item.payment_certificate_id === certificateId);
  const canReview = role === 'project_director';
  return <section className="space-y-5">
    <header className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="text-lg font-extrabold text-slate-900">Payment certificates</h2><p className="mt-1 text-sm text-slate-600">Financial authorization from certified progress. A certified certificate is still <strong>payment pending</strong>—it is not a bank payment.</p></header>
    {error && <p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-900">{error}</p>}{message && <p className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{message}</p>}
    <form onSubmit={event => { event.preventDefault(); void command({ action: 'create', ...form }); setForm({ valuationPeriodId: '', certificateNumber: '', certificateDate: today() }); }} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold text-slate-900">Create draft payment certificate</h3><div className="mt-3 grid gap-3 md:grid-cols-3"><select required value={form.valuationPeriodId} onChange={event => setForm({ ...form, valuationPeriodId: event.target.value })} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"><option value="">Select certified IPC valuation</option>{(data.certifiedValuations || []).map((item: any) => <option key={item.id} value={item.id}>{item.reference_number} · certified {item.certified_at?.slice(0, 10) || '—'}</option>)}</select><input required value={form.certificateNumber} onChange={event => setForm({ ...form, certificateNumber: event.target.value })} placeholder="Certificate number" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"/><BsDatePicker value={form.certificateDate} onChange={value => setForm({ ...form, certificateDate: value })}/></div><button disabled={busy} className="mt-3 rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">Create certificate draft</button></form>
    <div className="space-y-4">{(data.certificates || []).map((certificate: any) => { const source = valuations[certificate.valuation_period_id]; const certificateDeductions = deductions(certificate.id); return <article key={certificate.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-bold text-slate-900">{certificate.certificate_number}</h3><p className="text-sm text-slate-600">Source IPC: {source?.reference_number || certificate.valuation_period_id} · {certificate.certificate_date} · <span className="font-semibold">{certificate.status}</span> · Payment pending</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setSelectedRecord({ ...certificate, source_ipc: source, deductions: certificateDeductions })} className="rounded-md border border-slate-300 px-3 py-1.5 text-xs font-bold text-slate-800">View details</button>{certificate.status === 'draft' && <button disabled={busy} onClick={() => void command({ certificateId: certificate.id, action: 'submit' }, 'PATCH')} className="rounded-md bg-blue-700 px-3 py-1.5 text-xs font-bold text-white">Submit</button>}{certificate.status === 'submitted' && canReview && <button disabled={busy} onClick={() => void command({ certificateId: certificate.id, action: 'review' }, 'PATCH')} className="rounded-md border border-blue-300 px-3 py-1.5 text-xs font-bold text-blue-800">Review</button>}{certificate.status === 'review' && canReview && <button disabled={busy} onClick={() => void command({ certificateId: certificate.id, action: 'approve' }, 'PATCH')} className="rounded-md border border-amber-300 px-3 py-1.5 text-xs font-bold text-amber-800">Approve</button>}{certificate.status === 'approved' && canReview && <button disabled={busy} onClick={() => void command({ certificateId: certificate.id, action: 'certify' }, 'PATCH')} className="rounded-md bg-emerald-700 px-3 py-1.5 text-xs font-bold text-white">Certify</button>}</div></div>
      <dl className="mt-4 grid gap-3 rounded-lg bg-slate-50 p-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Gross certified amount</dt><dd className="mt-1 font-bold text-slate-900">{money(certificate.gross_certified_amount)}</dd></div><div><dt className="text-slate-500">Explicit deductions</dt><dd className="mt-1 font-bold text-slate-900">{money(certificate.total_deductions)}</dd></div><div><dt className="text-slate-500">Net certified amount</dt><dd className="mt-1 font-bold text-emerald-800">{money(certificate.net_certified_amount)}</dd></div></dl>
      {certificate.status === 'draft' && <form onSubmit={event => { event.preventDefault(); void command({ action: 'add_deduction', certificateId: certificate.id, kind: deduction.certificateId === certificate.id ? deduction.kind : 'retention', amount: Number(deduction.certificateId === certificate.id ? deduction.amount : 0), description: deduction.certificateId === certificate.id ? deduction.description : '' }); setDeduction({ certificateId: '', kind: 'retention', amount: '', description: '' }); }} className="mt-4 grid gap-2 rounded-lg border border-slate-200 p-3 md:grid-cols-4"><select value={deduction.certificateId === certificate.id ? deduction.kind : 'retention'} onChange={event => setDeduction({ ...deduction, certificateId: certificate.id, kind: event.target.value })} className="rounded border border-slate-300 bg-white px-2 py-2 text-sm text-slate-900"><option value="retention">Retention</option><option value="advance_recovery">Advance recovery</option><option value="other_contract_deduction">Other contract deduction</option></select><input required min="0" step="0.01" type="number" value={deduction.certificateId === certificate.id ? deduction.amount : ''} onChange={event => setDeduction({ ...deduction, certificateId: certificate.id, amount: event.target.value })} placeholder="Amount" className="rounded border border-slate-300 bg-white px-2 py-2 text-sm text-slate-900"/><input value={deduction.certificateId === certificate.id ? deduction.description : ''} onChange={event => setDeduction({ ...deduction, certificateId: certificate.id, description: event.target.value })} placeholder="Reason / reference" className="rounded border border-slate-300 bg-white px-2 py-2 text-sm text-slate-900"/><button disabled={busy} className="rounded border border-blue-300 px-3 py-2 text-sm font-bold text-blue-800">Add deduction</button></form>}
      {!!certificateDeductions.length && <ul className="mt-3 divide-y divide-slate-100 rounded-lg border border-slate-200 text-sm">{certificateDeductions.map((item: any) => <li key={item.id} className="flex items-center justify-between gap-3 p-2"><span className="text-slate-700">{String(item.deduction_kind).replaceAll('_', ' ')}{item.description ? ` · ${item.description}` : ''}</span><span className="flex items-center gap-2"><b className="font-semibold text-slate-900">{money(item.amount)}</b>{certificate.status === 'draft' && <button disabled={busy} onClick={() => void command({ certificateId: certificate.id, deductionId: item.id, action: 'remove_deduction' }, 'PATCH')} className="text-xs font-bold text-rose-700">Remove</button>}</span></li>)}</ul>}
    </article>; })}{!(data.certificates || []).length && <p className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">No payment certificates yet. Create one from a certified IPC valuation.</p>}</div>
    <RecordDetailsDialog title="Payment certificate" record={selectedRecord} onClose={() => setSelectedRecord(null)} />
  </section>;
}
